# services definition for this particular bundle
services:
#    servicios para proformas
    mayorbundle.proformas_service:
        class: Novamoda\MayorBundle\Services\ProformasService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para proformas
    mayorbundle.marcas_service:
        class: Novamoda\MayorBundle\Services\MarcasService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para proformas
    mayorbundle.almacen_service:
        class: Novamoda\MayorBundle\Services\AlmacenesService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para proformas
    mayorbundle.empleados_service:
        class: Novamoda\MayorBundle\Services\EmpleadosService
        arguments: ["@doctrine.orm.entity_manager"]

#    servicios para proformas
    mayorbundle.clientes_service:
        class: Novamoda\MayorBundle\Services\ClientesService
        arguments: ["@doctrine.orm.entity_manager"]